# Generated by Django 5.0.2 on 2024-03-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bogpost',
            new_name='Blogpost',
        ),
    ]
