# Generated by Django 5.0.2 on 2024-03-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_head1_blogpost_head2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
